# Generated by Django 2.1.4 on 2019-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
